const mongoose = require("mongoose");
const { Schema } = mongoose;
const ContactSchema = new mongoose.Schema({
  location_id: { type: String, },
  contact_id: { type: String, required: true, unique: true },
  name: { type: String, },
  email: { type: String, lowercase: true, default: null },
  phone: { type: String, },
  address: { type: String, },
  city: { type: String, },
  state: { type: String, },
  postal_code: { type: String, },
  country: { type: String, },
  company: { type: String, },
  website: { type: String, },
  source: { type: String, },
  type: { type: String, },
  assigned_to: { type: String, },
  profile_image: { type: String, },
  tags: { type: [String], default: [] }
  ,
  followers: { type: Array, default: [] },
  additional_emails: { type: Array, default: [] },
  additional_phones: { type: Array, default: [] },
  attributions: { type: Array, default: [] },
  custom_fields: { type: Array, default: [] },
  dnd: { type: Boolean, default: false },
  dnd_settings_email: { type: Boolean, },
  dnd_settings_sms: { type: Boolean, },
  dnd_settings_call: { type: Boolean, },
  inbound_dnd_settings: { type: mongoose.Schema.Types.Mixed, default: {} },
  date_added: { type: Date, },
  date_updated: { type: Date, },
  date_of_birth: { type: Date, },
  created_by: { type: String, },
  last_updated_by: { type: String, },
  facebook_id: { type: String, },
  instagram_id: { type: String, },
  linkedIn_lead_id: { type: String, },
  facebook_lead_id: { type: String, },
  client_portal_id: { type: String, },
  last_activity: { type: Date, },
  last_conversation_id: { type: String, },
  last_conversation_message_type: { type: Number, },
  conversations: { type: Array, default: [] },
  is_valid_whatsapp: { type: Boolean, },
  qbo_id: { type: String, },
  qbo_sync_token: { type: String, },
  Project_date: { type: Date, default: null },
  appointment_id: { type: String, default: null },
}, { timestamps: true });

module.exports = mongoose.model("Contact", ContactSchema);
